language: node_js
node_js:
  - "6"
  - "10"
  - "12"
  - "14"

install:
  - npm install
  - npm ci
  - npm run generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
